spring:
  datasource:
    druid:
      url: "jdbc:mysql://10.3.50.156:3306/smart_ums_member?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false"
      username: root
      password: root
  cloud:
    nacos:
      discovery:
        server-addr: "10.3.50.45:8848"
    # 将应用程序注册Sentinel
    sentinel:
      transport:
        dashboard: "10.3.50.45:8088"

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  sentinel:
    enabled: true

#error
#  info 生产环境日志级别
logging:
  level:
    # 开发日志级别
    com.smart.member.mapper: debug

#<bean id class="SQLsessionfactory" >
#<property url= "">
#<property username= "root">
#<property url= "">
#<property url= "">

#</bean>