server:
  port: 8091

spring:
  application:
    name: smart-member
  profiles:
    active: common-mysql,dev




shiro:
  path-list:
    - "/member/login"
    - "/member/register"
    - "/noauth"
    - "/member/orders"
  logout-path: "/member/logout"
  loginUrl: /noauth
