server:
  port: 9990
  servlet:
    context-path: /auth

# 核心配置 其它省略
jwt:
  # 密匙KEY
  secret: afafsfdsfsf
  # Header KEY
  token-header: Authorization
  # Token前缀字符
  token-prefix: smart-
  # 过期时间 单位秒 1天后过期=86400 7天后过期=604800
  expiration: 86400
  # 配置不需要认证的接口
  # 有效时间
  valid-time: 7

white:
  ant-matchers:
    - "/auth/login"
spring:
  application:
    name: smart-auth
  cloud:
    nacos:
      discovery:
        server-addr: "10.3.50.45:8848"

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
