server:
  port: 8880
spring:
  application:
    name: smart-pay-ali
  cloud:
    nacos:
      discovery:
        server-addr: "10.3.50.45:8848"
        namespace: 310ead47-2894-46c0-a656-055ee6cf4be7
dubbo:
  protocol:
    serialization: kryo
    name: "dubbo"
    port: -1
  registry:
    address: nacos://${spring.cloud.nacos.discovery.server-addr}
    parameters[namespace]: ${spring.cloud.nacos.discovery.namespace}
  scan:
    base-packages: com.smart.ali.service.impl

pay:
  ali:
    protocol: "https"
    gateway-host: "openapi.alipaydev.com"
    sign-type: "RSA2"
    app-id: "2016072900120438"
    private-key: "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC2Rl0PaZu+SLL0BVkKFyysYiNPkdOdA1l8AX/pP4xfRlV4NnPudpfhsqZnFU8BDCCiPAoB0QwfTAfOvyLeIyGD4M/qoANkTTnjMEcs1VKK7M7eTz50xOZFkXeQoaByzA35CLOX5hcY8L/0QjiJUJ6Rw6DqO7OV8lP+1jT8IG6ad2Htx33XZBo4vahokZcjHcfnYG06a9IU/GdF08XnBbSb8XnGetDUJIP8JCnnkX2omL87X+ccrkmps0s7BoNqExqhmCzwaK5WujtDi+i0qw5LcbXdws/wU/NOC5ES91Dv4N60dTnJxA4cUBiG+j//zxm6S83PLicfPq+safsbbeuJAgMBAAECggEAe+67t48G5gpoIqLAN6wqI8tWVvO//jIY1cfvQJiEyQL5ehMMIEdiXYMqwUwru3qTdbt80l9g7qazaE9tVbxtPU3OEKlbpQcdJOveeQ1SYkNBJMacoKiAKS0PLre2cFdt6LWR5uX7LmoDGgEsj7DRICrzbk/Je1qY4dyjigpDKaJ520sbbDA8WcLUwWcauurhSlia1AEjzPoksrXJs7pFYHHt4rH0RVlDY9jCDIwuBA3YD7EAXFAivNn4hHxqojFI2BoQltUdKKiSIZR2DcclQkxfjGvb4+hJb9NZghSQ1aq/rZlPTe1AiDneTCDd7T9E6gklctNc1GNT48PtGO9wAQKBgQD32hW77BZRyPKDMk20yCO/6OzVo8WZnS+Heoi8RDWMueRiG6tPvvgA1ofSBub2t9Qio3Gxg21zJkbj8Gq5m5X9+vbHag/tFXCU/HR+TnOXkG3VCP2b6lzkJnAAqR9wW+X5HCPmhcuKLzmW9RxXv84CB48S835HMRGkCLaMIgZjYQKBgQC8RGJMlgat0Gg/M4gFFwPL8IO9kkKgEuIBo51rYqEhwTGAtNS0Jhn8aEaMDumdvE4OUF0oYKCIfWAlqzBt/EnwwCrz0DfqilT8WXATVlSV1mXyhXgIo09RkSbFVCk16fOauSx7k8cpoNNdxy+RNi9RAOGX3AEK/y4xYNRWFOihKQKBgBT8TSzNL5KbLhV3s+ajr4s3QJ5SMI/yJC0Xbe5q5BHXR4QbDaVB6SPBBlz9Ip8vL3IDXsQF+cVvLz9rgs3WY5vOnQiDbXfIgfDLc12ibN0faH1KNpb2AAl9S6xypWvRDCbMgCmrmHFJ0Fl8xXqUje/UDgQvw7hpajH2XuZ8lwfhAoGAUMKA7Ft69/qrjVj8ozpRLZ251Ys1O1d+Tbey4orHliQ6qPxpNfIWOZk9kf0fp8NMNIWywIxasNIfeWkq+DM+QKEei8IpClpWxH1VP2ZMGI6E4vjwGbx8XQAIAqPsna0DC78dXtFwoOHVaaf1NrRorbXUEAGXDPGUDih8TYTgmakCgYEAv5F9P4ELoPJhgUnXn13kQ+GBEEcmJOUin4YHl8MNjKf5WyxXJDXS6EzPx1If+W32blGnnWN74dzcu7Y3AGmaK5IAA+RcmUJYT5Z+Cq8pI9Ow4sHxmDdlA+QNSKTtsCr99R5cJ6EgwKtyry0fVjih2tEkAk+sX4gR7INezxyuIGU="
    alipay-public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxigwxX2h/SYIttlcslO585rqM0ZuqF+9DJUWRS+P7NevCK+oOhm69/iSk/f/K7Mtna0VudlDBIqd1kJ57236Ln4+hoH9SquwoLzIkpt8oYJQ4pJ0J7fFhUdvvnAfpcbkOJnlBWUjD6oJGXkkI3aBzXWlTSuays8+nNIPavvnadjz9ynleBKHWb7/Bw4s2Zm4UT5xLwYPPf2vX8WSkv10PS2SzW2HxuKb8l++eiVmkb91rVzQ9TAtRHRA/q+5zCQHvhKW5HNKJTLayvKxxxIgvAPHsog+6ViIWbmEX1G4rby8E7MPawUlGozmEGoXlSzrUuuVZH97CPOeMAJvRjYnVQIDAQAB"
    charset: "UTF-8"
    return_url: "支付成功跳转的界面"
    notify_url: "xxx:/pay/back"
